#!/bin/bash

# Return values from update-check --check-only
UPTODATE=2
UPDATENEEDED=3

# Length of time Zenity stays on screen before timeout
DIALOGTIMEOUT=30

# Name of program to log
LOGGERNAME="update_user_cancel"
# Create easy logger command
LOGGER="logger -it $LOGGERNAME"

# Star
echo "Starting $LOGGERNAME" | $LOGGER

    echo "No active session detected, checking for new firmware version" | $LOGGER
    #get latest settings from UMS 
    get_rmsettings
    #Check if update is needed
    CURRENTFIRMWARE=$(cat /etc/os-release | grep VERSION= | egrep -o "([0-9]{1,}\.)+[0-9]{1,}");
    UPDATECHECKRESPONSE=$(update-check --check-only)
    UPDATESTATUS=$?
    if [ $UPDATESTATUS -eq $UPTODATE ]; then
        echo "$UPDATECHECKRESPONSE" | $LOGGER
        exit 0
        else
        echo "Current Firmware: $CURRENTFIRMWARE -- $UPDATECHECKRESPONSE" | $LOGGER
        DISPLAY=:0 zenity --question --text "Update needed $UPDATECHECKRESPONSE\nUpdate NOW?" --width=175 --height=100 --timeout=$DIALOGTIMEOUT --ok-label="Update" --cancel-label="Cancel"
        DIALOGRESPONSE=$?
        if [ $DIALOGRESPONSE -eq 0 ]; then
            echo "Updating firmware per user request" | $LOGGER
            update
        elif [ $DIALOGRESPONSE -eq 5 ]; then 
            echo "Update dialog timed out. Firmware not updated" | $LOGGER
        elif [ $DIALOGRESPONSE -eq 1 ]; then
            echo "User cancelled. Firmware not update" | $LOGGER
        fi
    fi